const file = {
  bucket: 'personal',
  bytesSize: '134.83 KB',
  created: new Date(),
  dbId: undefined,
  error: false,
  ext: 'html',
  fullKey: 'personal/index2.html',
  id: 'personal/index2.html',
  ipfsHash: '',
  isAvailableInSpace: true,
  isLocallyAvailable: true,
  isPublicLink: false,
  isUploading: false,
  key: 'index2.html',
  lastModified: new Date(),
  members: [],
  name: 'index2.html',
  pivote: true,
  selected: false,
  shareAmount: 1,
  sharedBy: undefined,
  size: 138071,
  sourceBucket: 'personal',
  sourcePath: '',
  type: 'file',
};

export default file;
