export { default as Folder } from './Folder';
export { default as PDF } from './PDF';
export { default as Zip } from './Zip';
export { default as Powerpoint } from './Powerpoint';
export { default as Word } from './Word';
export { default as Image } from './Image';
export { default as Audio } from './Audio';
export { default as Video } from './Video';
export { default as Default } from './Default';